services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: lab_01_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/volumes/postgres_data
